// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcwlmmxaszixdrpdofnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjd2xtbXhhc3ppeGRycGRvZm5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4Njg1MjcsImV4cCI6MjA1MjQ0NDUyN30.LcTI-0EgHuGtie7qB0ki9W_FFCiw9iJgNyJVwE_XBTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);